global:
  scrape_interval: 30s
  scrape_timeout: 5s
  evaluation_interval: 30s
scrape_configs:
- job_name: kubernetes-apiservers
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: default;kubernetes;https
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_name
    - __meta_kubernetes_endpoint_port_name
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

- job_name: kubernetes-nodes-kubelet
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - target_label: __address__
    regex: "(.+):10250"
    source_labels: [__address__]
    replacement: "${1}:10255"

- job_name: kubernetes-nodes-cadvisor
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - target_label: __metrics_path__
    replacement: /metrics/cadvisor
  - target_label: __address__
    regex: "(.+):10250"
    source_labels: [__address__]
    replacement: "${1}:10255"

# Configuration for the port (prometheus.io/port) that service endpoints are
# annotated with.
- job_name: kubernetes-service-endpoints
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
  - action: replace
    regex: (https?)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scheme
    target_label: __scheme__
  - action: replace
    regex: (.+)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_path
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels:
    - __address__
    - __meta_kubernetes_service_annotation_prometheus_io_port
    target_label: __address__
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: k8s_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_service_name
    target_label: k8s_service
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: k8s_pod

rule_files:
- "oc.rules.yml"
- "slos.rules.yml"
